# Generated by Django 6.1 on 2026-09-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiltotp',
            name='secret',
            field=models.CharField(max_length=255),
        ),
    ]
