# Generated by Django 6.1 on 2026-09-20 20:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0002_alter_perfiltotp_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiltotp',
            name='aceita_comunicacoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfiltotp',
            name='data_atualizacao_consentimento',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfiltotp',
            name='data_consentimento',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfiltotp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_totp', to=settings.AUTH_USER_MODEL),
        ),
    ]
