# Generated by Django 6.1 on 2026-09-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0003_perfiltotp_aceita_comunicacoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegridadeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('actual_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
